{{- if .Values.ingress.enabled -}}
{{- $fullName := include "helm.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-ingress
  namespace: {{ .Release.Namespace }}
spec:

  rules:
    - host: dashboard.com
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}
              servicePort: 10000
{{- end }}
