apiVersion: v1
kind: Service
metadata:
  name: trackingservice
  namespace: {{ .Release.Name }}
  annotations:
    sds/load-ports-as-separate-services: "true"
spec:
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
  ports:
    - name: server
      port: 10000
      targetPort: 5000
  type: LoadBalancer
