apiVersion: v1
kind: Service
metadata:
  name: tracking-external-service
  namespace: {{ .Release.Name }}
spec:
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
  ports:
    - port: 5000
      targetPort: 5000
